### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by swapnil2222** [swapnil2222/spotify-music-player#2]
- [ ] Add typescript support
- [ ] Add scss support
- [ ] Add to playlist functionality
- [ ] Deploy application
- [ ] CI/CD pipeline
- [ ] Stream song online
- [ ] Integrate spotify playlist
- [ ] load songs from folder
